### ISSUE TITLE
Replace zedpac C 

### ISSUE THREAD

**Issue by deitch** [zededa/go-provision#354]
The only reason we use `CGO_ENABLED=1` is because of `zedpac`. That, in itself, is just a single function that makes other calls. We should replace this with native go code when possible.

**Comment by rvs** [comment]
Actually no -- its not a single function -- it is an entire implementation of the duktape JavaScript engine that we're embedding -- replacing it will be pretty difficult.

Btw, @deitch we should probably start opening up issue up in EVE repo since this one won't transition to LF Edge.

**Comment by deitch** [comment]
> we should probably start opening up issue up in EVE repo since this one won't transition to LF Edge.

Good point. I am going to move this one over there and close it here.
